NODIR: str = "ERROR: No such directory"
NOFILE: str = "ERROR: No such file in directory"
BADINPUT: str = "ERROR: Wrong command input"
FAILED: str = "ERROR: Could not execute command"
CANCEL: str = "Execution cancelled"
INVANS: str = "Invalid answer, try again"
RMREST: str = "ERROR: cannot delete root or parent directory"